(package "jcs-frametitle"
         "0.1.0"
         "An frame title for jcs-emacs")

(website-url "https://github.com/jcs-emacs/jcs-frametitle")
(keywords "faces" "frame-title")

(package-file "jcs-echobar.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "27.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
